"""empty message

Revision ID: 27a5296b609a
Revises: 4cd3faa00a1f
Create Date: 2022-05-21 22:05:04.678196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a5296b609a'
down_revision = '4cd3faa00a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=64), nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
