"""empty message

Revision ID: 43a8d7fc2010
Revises: 
Create Date: 2022-05-22 19:56:19.251399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a8d7fc2010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_animal_name'), 'animal', ['animal_name'], unique=True)
    op.create_table('continent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continent_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continent_continent_name'), 'continent', ['continent_name'], unique=False)
    op.create_table('puzzle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('server_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_date', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_type'), 'type', ['type'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('continent_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=False)
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('animal_id', sa.String(length=64), nullable=False),
    sa.Column('country_id', sa.String(length=64), nullable=False),
    sa.Column('mouldy', sa.Boolean(), nullable=True),
    sa.Column('image_filename', sa.String(length=128), nullable=False),
    sa.Column('image_attribution', sa.String(length=128), nullable=True),
    sa.Column('info_link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheese_cheese_name'), 'cheese', ['cheese_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheese_cheese_name'), table_name='cheese')
    op.drop_table('cheese')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_type_type'), table_name='type')
    op.drop_table('type')
    op.drop_table('puzzle_history')
    op.drop_index(op.f('ix_continent_continent_name'), table_name='continent')
    op.drop_table('continent')
    op.drop_index(op.f('ix_animal_animal_name'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
