"""empty message

Revision ID: 442d6554cad4
Revises: 
Create Date: 2022-05-22 18:41:19.183103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442d6554cad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_animal_name'), ['animal_name'], unique=True)

    op.create_table('continent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continent_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_continent_continent_name'), ['continent_name'], unique=False)

    op.create_table('puzzle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('server_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_date', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_type'), ['type'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'role_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('continent_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_country_name'), ['country_name'], unique=False)

    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('animal_id', sa.String(length=64), nullable=False),
    sa.Column('country_id', sa.String(length=64), nullable=False),
    sa.Column('mouldy', sa.Boolean(), nullable=True),
    sa.Column('image_filename', sa.String(length=128), nullable=False),
    sa.Column('image_attribution', sa.String(length=128), nullable=True),
    sa.Column('info_link', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheese_cheese_name'), ['cheese_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheese_cheese_name'))

    op.drop_table('cheese')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_country_name'))

    op.drop_table('country')
    op.drop_table('user')
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_type'))

    op.drop_table('type')
    op.drop_table('role')
    op.drop_table('puzzle_history')
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continent_continent_name'))

    op.drop_table('continent')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_animal_name'))

    op.drop_table('animal')
    # ### end Alembic commands ###
