"""empty message

Revision ID: cff6e367bad9
Revises: 4cd3faa00a1f
Create Date: 2022-05-21 22:20:07.178234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff6e367bad9'
down_revision = '4cd3faa00a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzle_date', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_history', schema=None) as batch_op:
        batch_op.drop_column('puzzle_date')

    # ### end Alembic commands ###
