"""empty message

Revision ID: eb3de6ff1559
Revises: 934f6ae5d603
Create Date: 2022-05-18 19:28:07.730153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3de6ff1559'
down_revision = '934f6ae5d603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheese', sa.Column('image_filename', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheese', 'image_filename')
    # ### end Alembic commands ###
